name: Backend CI/CD Pipeline

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_SERVER_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_SERVER_PROJECT_ID }}

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies and build
        working-directory: ./server
        run: |
          npm ci
          npm run

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel environment info
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Add CORS environment variable
        run: |
          vercel env add ALLOWED_ORIGIN "${{ secrets.ALLOWED_ORIGIN || 'https://not-uygulamasi-client.vercel.app' }}" production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build with Vercel
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Production
        run: |
          vercel deploy --prod --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
          vercel alias set $(vercel ls --prod --token=${{ secrets.VERCEL_TOKEN }} | grep -o 'https://[^ ]*') not-uygulamasi-server.vercel.app --token=${{ secrets.VERCEL_TOKEN }}