name: Production Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Vercel Project Info
        run: |
          project_name=$(curl -s "https://api.vercel.com/v9/projects/${{ secrets.VERCEL_PROJECT_ID }}" \
            -H "Authorization: Bearer ${{ secrets.VERCEL_API_TOKEN }}" \
            | jq -r .name)
          echo "Vercel Project Name: $project_name"
          echo "PROJECT_NAME=$project_name" >> $GITHUB_ENV

      - name: Install Vercel CLI
        run: npm install --global vercel@latest
        
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Frontend
        working-directory: ./client
        run: |
          npm ci
          npm run build

      - name: Deploy Frontend to Vercel
        run: |
          url="$(vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }})"
          vercel alias --token=${{ secrets.VERCEL_TOKEN }} set "$url" not-uygulamasi-client.vercel.app

  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Vercel Project Info
        run: |
          project_name=$(curl -s "https://api.vercel.com/v9/projects/${{ secrets.VERCEL_SERVER_PROJECT_ID }}" \
            -H "Authorization: Bearer ${{ secrets.VERCEL_API_TOKEN }}" \
            | jq -r .name)
          echo "Vercel Project Name: $project_name"
          echo "PROJECT_NAME=$project_name" >> $GITHUB_ENV

      - name: Install Vercel CLI
        run: npm install --global vercel@latest
        
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Add Environment Variables
        run: |
          vercel env add ALLOWED_ORIGIN "https://not-uygulamasi-client.vercel.app" --token=${{ secrets.VERCEL_TOKEN }}
          vercel env add NODE_ENV "production" --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build and Deploy Backend
        run: |
          url="$(vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }})"
          vercel alias --token=${{ secrets.VERCEL_TOKEN }} set "$url" not-uygulamasi-server.vercel.app 