name: Pull Request CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '**'  # Tüm branchler için

jobs:
  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install Frontend Dependencies
        working-directory: ./client
        run: npm ci

      - name: Run Frontend Tests
        working-directory: ./client
        run: npm test -- --ci --updateSnapshot=false

  lint:
    name: Lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install Frontend Dependencies
        working-directory: ./client
        run: npm ci

      - name: Install Backend Dependencies
        working-directory: ./server
        run: npm ci

  build-check:
    name: Build Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Build Frontend
        working-directory: ./client
        run: |
          npm ci
          npm run build

      - name: Check Backend
        working-directory: ./server
        run: |
          npm ci
          npm run

  status-check:
    name: Final Status Check
    needs: [frontend-tests, lint, build-check]
    runs-on: ubuntu-latest
    steps:
      - name: Check Status
        run: echo "All checks passed successfully!" 
